export { Problem } from "./Problem";
export { Approach } from "./Approach";
export { Services } from "./Services";
export { Process } from "./Process";
export { Work } from "./Work";
export { SocialProof } from "./SocialProof";
export { Testimonials } from "./Testimonials";
export { About } from "./About";
export { FinalCTA } from "./FinalCTA";
